version: '3'

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend

  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - django

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: SistemaCredito_db
      POSTGRES_USER: Rdemora2
      POSTGRES_PASSWORD: rdemora2dbpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: